### ISSUE TITLE
Personalized model for clients

### ISSUE THREAD

**Issue by pone7** [facebookresearch/FLSim#40]
## ❓ Questions and Help

Until we move the questions to another medium, feel free to use this as your question:

## Question

Is it possible to deploy different models to clients? For example, deploy only a part of the model on the server.

**Comment by JohnlNguyen** [comment]
Hi, it is possible. You can do so by modifying this loop

https://github.com/facebookresearch/FLSim/blob/main/flsim/trainers/sync_trainer.py#L389
